mod.name=RankSpoof
mod.description=A mod to spoof your Hypixel Rank.
mod.id=rankspoof
mod.group=dev.cxntered
mod.version=1.2.0
mod.mc_version=1.8.9

publish.modrinth.id=9Lyxhh7B
publish.github.repo=cxntered/RankSpoof
publish.github.branch=legacy/ornithe

org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=true
